### ISSUE TITLE
Consent Form

### ISSUE THREAD

**Issue by andero2003** [SofEng-Coursework/OurProject#19]

**Comment by Antoine098** [comment]
https://docs.google.com/document/d/1npZCTkq2XTVtAatcOSkBkZWCdJj8ZMw2p1RfEdj7hVg/edit#heading=h.vg7gzpvoib1u

**Comment by Antoine098** [comment]
https://docs.google.com/document/d/1npZCTkq2XTVtAatcOSkBkZWCdJj8ZMw2p1RfEdj7hVg/edit#heading=h.qnb8b31w14ri

**Comment by tommydoe1** [comment]
https://docs.google.com/document/d/195HJ1dNKq9_dUOXlLOocGk5FmBPIFo_E/edit?usp=sharing&ouid=112207039927439745935&rtpof=true&sd=true
